name: Plumber

on:
  push:
    branches: [main]
  pull_request: null

permissions:
  contents: read
  security-events: write
  id-token: write   # uncomment to enable score-push below

jobs:
  plumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: getplumber/plumber@87ca135cc4566ba8e9065ea95b5d897232cdb208 # July 20, 2026, v0.4.16
        with:
          # Set to `true` to publish an official Plumber score badge
          # (it makes your score and repo name public, see Score Push section below)
          score-push: true
