name: Plumber

on:
  push:
    branches: [main]
  pull_request: null

permissions:
  contents: read
  security-events: write
  id-token: write # uncomment to enable score-push below

jobs:
  plumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: getplumber/plumber@c85c712bca3c9f547a88c66bb2541db179a1a79e # ratchet:getplumber/plumber@v0.4.52
        with:
          # Set to `true` to publish an official Plumber score badge
          # (it makes your score and repo name public, see Score Push section below)
          score-push: true
